// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBwX6-5SXf0yzNN_5PCFdYwHcWbPMCxu2c',
    appId: '1:5635012430:web:7273bb1c0f5d600d90d01f',
    messagingSenderId: '5635012430',
    projectId: 'instate-bot-kpbb',
    authDomain: 'instate-bot-kpbb.firebaseapp.com',
    storageBucket: 'instate-bot-kpbb.firebasestorage.app',
    measurementId: 'G-D4BN5R2CN4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBZVASwz5vAFVN36_OiWF1Di0F4SvHpiK0',
    appId: '1:5635012430:android:df05b0aa9a67348790d01f',
    messagingSenderId: '5635012430',
    projectId: 'instate-bot-kpbb',
    storageBucket: 'instate-bot-kpbb.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAT-sJJ1ZaSrgyHyQsUSDw1PxsYLORI_3A',
    appId: '1:5635012430:ios:0cd6c13e93f4294390d01f',
    messagingSenderId: '5635012430',
    projectId: 'instate-bot-kpbb',
    storageBucket: 'instate-bot-kpbb.firebasestorage.app',
    iosBundleId: 'com.example.instateApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAT-sJJ1ZaSrgyHyQsUSDw1PxsYLORI_3A',
    appId: '1:5635012430:ios:0cd6c13e93f4294390d01f',
    messagingSenderId: '5635012430',
    projectId: 'instate-bot-kpbb',
    storageBucket: 'instate-bot-kpbb.firebasestorage.app',
    iosBundleId: 'com.example.instateApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBwX6-5SXf0yzNN_5PCFdYwHcWbPMCxu2c',
    appId: '1:5635012430:web:96a47fb2a5234da190d01f',
    messagingSenderId: '5635012430',
    projectId: 'instate-bot-kpbb',
    authDomain: 'instate-bot-kpbb.firebaseapp.com',
    storageBucket: 'instate-bot-kpbb.firebasestorage.app',
    measurementId: 'G-MPGMZDSGTR',
  );
}
